// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Supabase transaction pooler — used at runtime, survives serverless cold starts
    url: process.env['DATABASE_URL'],
    // Supabase direct connection — used by `prisma migrate dev` only
    directUrl: process.env['DIRECT_URL'],
  },
})
